name: fireguard_ai
description: Flutter app for FireGuard AI - real-time fire detection monitoring with Firebase.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_core: ^3.4.0
  firebase_database: ^11.0.3
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
